# Build / Publish
FROM streetcred/dotnet-indy:1.15.0 AS build
RUN mkdir -p /app/src
WORKDIR /app/src

# Only copy dependency file to benefit from Docker layer caching
COPY dotnet/server/DotNet.Backchannel.csproj ./DotNet.Backchannel.csproj
RUN dotnet restore "DotNet.Backchannel.csproj"

COPY dotnet/server .
RUN dotnet publish "DotNet.Backchannel.csproj" -c Release -o /app/build

# Run
FROM streetcred/dotnet-indy:1.15.0 AS final
RUN mkdir -p /aries-backchannels
WORKDIR /aries-backchannels
COPY --from=build /app/build /aries-backchannels

ENV RUNMODE=docker

ENTRYPOINT ["dotnet", "DotNet.Backchannel.dll"]