FROM python:3.13-slim-bullseye

RUN mkdir -p /aries-backchannels
WORKDIR /aries-backchannels

RUN apt-get update \
   && apt-get install -y git gnupg2 software-properties-common curl \
   && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CE7709D068DB5E88 \
   && apt-get update \
   && apt-get install -y software-properties-common \
   && apt-get update

ENV RUNMODE=docker

COPY python/requirements.txt python/
RUN pip install -r python/requirements.txt
COPY mobile/requirements.txt mobile/
RUN pip install -r mobile/requirements.txt

# Copy the necessary files from the AATH Backchannel sub-folders
COPY python python
COPY mobile mobile
COPY data ./

ENV PYTHONPATH=/aries-backchannels

ENTRYPOINT ["python", "mobile/mobile_backchannel.py"]
