FROM docker.pkg.github.com/hyperledger/aries-vcx/libvcx:0.17.3

USER root

ARG UID=1001
ARG GID=1001

RUN addgroup -g $GID agent && adduser -u $UID -D -G agent agent

WORKDIR home/agent/aries-vcx-backchannel/aries-vcx
COPY --chown=agent:agent aries-vcx .
RUN chown -R agent:agent .

USER agent

RUN cargo build

ENTRYPOINT ["./target/debug/aries-vcx-backchannel"]
