name: test-harness-acapy-credo
# RUNSET_NAME: "ACA-PY to Credo"
# Scope: AIP 1.0
# Exceptions: Revocation
#
# Summary
#
# This runset uses the current main branch of ACA-Py for all of the agents except Bob (holder),
# which uses the master branch of Credo TS. The runset covers all of the AIP 1.0 tests
# except those that are known **not** to work with the Credo TS as the holder,
# notably those that involve revocation notification v1.
#
# Current
#
# Most of the tests are running. The tests not passing are being investigated.
#
# *Status Note Updated: 2024.09.06*
#
# End
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      LEDGER_URL_CONFIG: "http://localhost:9000"
      TAILS_SERVER_URL_CONFIG: "http://localhost:6543"
      START_TIMEOUT: 120
    steps:
      - name: checkout-test-harness
        uses: actions/checkout@v4
        with:
          path: test-harness
      - name: run-von-network
        uses: ./test-harness/actions/run-von-network
      - name: run-indy-tails-server
        uses: ./test-harness/actions/run-indy-tails-server
      - name: run-test-harness-wo-reports
        id: run_test_harness
        uses: ./test-harness/actions/run-test-harness-wo-reports
        with:
          BUILD_AGENTS: "-a acapy-main -a credo"
          TEST_AGENTS: "-d acapy-main -b credo"
          TEST_SCOPE: "-t @AcceptanceTest -t @AIP10,@RFC0441,@RFC0211,@T001-RFC0453,@RFC0023 -t ~@wip -t ~@T004-RFC0211 -t ~@QualifiedDIDs -t ~@T001-RFC0183"
          REPORT_PROJECT: acapy-b-credo
      - name: run-send-gen-test-results-secure
        if: ${{ steps.run_test_harness.conclusion == 'success' }}
        uses: ./test-harness/actions/run-send-gen-test-results-secure
        with:
          REPORT_PROJECT: acapy-b-credo
          ADMIN_USER: ${{ secrets.AllureAdminUser }}
          ADMIN_PW: ${{ secrets.AllureAdminPW }}
