name: test-harness-credo-acapy
# RUNSET_NAME: "Credo to ACA-PY"
# Scope: AIP 1.0
# Exceptions: Proof Proposal
#
# Summary
#
# This runset uses the current master branch of Credo TS for all of the agents except Bob (holder),
# which uses the main branch of ACA-Py. The runset covers all of the AIP 1.0 tests
# except those that are known **not** to work with the Credo TS
#
# Current
#
# All AIP10 tests are currently running.
# OOB & DID Exchange Tests are running. 
#
# *Status Note Updated: 2024.10.29*
#
# End
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      LEDGER_URL_CONFIG: "http://localhost:9000"
      TAILS_SERVER_URL_CONFIG: "http://localhost:6543"
    steps:
      - name: checkout-test-harness
        uses: actions/checkout@v4
        with:
          path: test-harness
      - name: run-von-network
        uses: ./test-harness/actions/run-von-network
      - name: run-indy-tails-server
        uses: ./test-harness/actions/run-indy-tails-server
      - name: run-test-harness-wo-reports
        id: run_test_harness
        uses: ./test-harness/actions/run-test-harness-wo-reports
        with:
          BUILD_AGENTS: "-a credo -a acapy-main"
          TEST_AGENTS: "-d credo -b acapy-main"
          TEST_SCOPE: "-t @AcceptanceTest -t ~@wip -t @AIP10,@RFC0211,@T001-RFC0453,@RFC0023 -t ~@Transport_NoHttpOutbound -t ~@QualifiedDIDs"
          REPORT_PROJECT: credo-b-acapy
      - name: run-send-gen-test-results-secure
        if: ${{ steps.run_test_harness.conclusion == 'success' }}
        uses: ./test-harness/actions/run-send-gen-test-results-secure
        with:
          REPORT_PROJECT: credo-b-acapy
          ADMIN_USER: ${{ secrets.AllureAdminUser }}
          ADMIN_PW: ${{ secrets.AllureAdminPW }}
